# Documentation/Reference: https://www.appveyor.com/docs/appveyor-yml/

# Semantic Versioning http://semver.org/
version: 0.0.{build}

image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - master

init:
- git config --global core.autocrlf true

install:
  - choco install gitversion.portable -pre -y

# clone directory
clone_folder: c:\projects\MiKo.Analyzers

# fetch repository as zip archive (when next line is uncommented)
# shallow_clone: true

# skip specific commits
skip_commits:
  files:
    - /*.md

before_build:
- nuget restore "c:\projects\MiKo.Analyzers\MiKo.Analyzer.sln"

# enable patching of AssemblyInfo.* files (seems to not work for .NET Core projects as it would for .NET standard projects)
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "{version}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"

build:
  parallel: true
  project: MiKo.Analyzer.sln
  verbosity: minimal

platform:
  - Any CPU

configuration:
#  - Debug
  - Release

# Currently, .NET Core 2.0 projects are not supported by NUnit 3, so we cannot yet run the tests (and same for Codecov code coverage)
# test_script:
# -  '%USERPROFILE%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:" "".\MiKo.Analyzer.Tests\bin\netcoreapp2.0\MiKoSolutions.Analyzers.Tests.dll"" --workers=16" -returntargetcode -filter:"+[MiKo*]* -[*Test*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -output:"c:\projects\MiKo.Analyzers\MiKoAnalyzers_coverage.xml" '

# Codecov Flags (https://docs.codecov.io/v4.3.6/docs/flags)
# - '%USERPROFILE%\.nuget\packages\Codecov\1.0.3\tools\codecov.exe -f "c:\projects\MiKo.Analyzers\MiKoAnalyzers_coverage.xml" -t 3599e0b3-8d22-44eb-a33d-58383db89b64 --flag api '

# Run SonarQube scanner


# cache:

